name: "Pull Request Triage"
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: ADEMOLA200/Ryujinx
          ref: develop

      - name: Update labels based on changes
        uses: actions/labeler@v5
        with:
          sync-labels: true
          dot: true
